
import { QUESTION_BANK } from '../data/questions.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, createUserWithEmailAndPassword, signInWithEmailAndPassword, onAuthStateChanged, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, addDoc, collection, getDocs, query, where, orderBy, limit, onSnapshot, serverTimestamp, increment, arrayUnion, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
const firebaseConfig={
  apiKey: "AIzaSyCNnyzZwuBasb_VhUmTXAWMxzOVMlg_LiA",
  authDomain: "projetos-klar.firebaseapp.com",
  projectId: "projetos-klar",
  storageBucket: "projetos-klar.firebasestorage.app",
  messagingSenderId: "484849594276",
  appId: "1:484849594276:web:f1e0a47beaba97cfecdb31",
  measurementId: "G-JEZ2GJKYED"
};
const app=initializeApp(firebaseConfig),auth=getAuth(app),provider=new GoogleAuthProvider(),db=getFirestore(app);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const el=document.createElement('div');el.className='toast';el.textContent=m;$('#toast').appendChild(el);setTimeout(()=>el.remove(),3800)};
const AVATARS=['pergaminho','cordeiro','leao','pomba','peixe','lampada','coroa','harpa','barco','oliveira','escudo','trombeta','biblia','estrela','monte','sem-foto'];
const BORDERS=['simples','bronze','prata','ouro','azul','pomba','fogo','coroa','oliveira','apocalipse','mestre','celestial'];
const TITLES=['Novo Discípulo','Aprendiz da Palavra','Jovem Bereano','Leitor Fiel','Conhecedor dos Evangelhos','Servo Prudente','Guardião da Palavra','Mensageiro da Fé','Mestre dos Evangelhos','Arauto do Apocalipse','Lenda da Mocidade'];
const MISSIONS=[{id:'daily10',type:'daily',name:'Responder 10 perguntas',target:10,key:'answeredToday',reward:50},{id:'daily5',type:'daily',name:'Acertar 5 perguntas hoje',target:5,key:'correctToday',reward:40},{id:'weekly100',type:'weekly',name:'Responder 100 perguntas na semana',target:100,key:'answeredWeek',reward:250},{id:'hard20',type:'weekly',name:'Acertar 20 difíceis/extremas',target:20,key:'hardCorrectWeek',reward:300},{id:'friend1',type:'permanent',name:'Enviar um convite de amizade',target:1,key:'friendInvites',reward:80},{id:'room1',type:'permanent',name:'Participar de uma sala',target:1,key:'roomsJoined',reward:100}];
let currentUser=null,profile=null,quiz=null,roomUnsub=null,selectedAvatar='pergaminho',selectedBorder='simples',selectedTitle='Novo Discípulo',isAdmin=false;
const categories=[...new Set(QUESTION_BANK.map(q=>q.category))].sort();
$('#soloCategory').innerHTML += categories.map(c=>`<option value="${c}">${c}</option>`).join('');
function todayKey(){return new Date().toISOString().slice(0,10)}
function weekKey(){const d=new Date();const y=d.getFullYear();const onejan=new Date(y,0,1);return y+'-W'+Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7)}
function monthKey(){return new Date().toISOString().slice(0,7)}
function pointsFor(q,fast=false){return ({facil:10,medio:20,dificil:35,extremo:60}[q.difficulty]||15)+(fast?5:0)}
function levelFor(xp){return Math.max(1,Math.floor(Math.sqrt((xp||0)/90))+1)}
function avatarSrc(p=profile){if(!p)return'assets/avatars/pergaminho.svg';if(p.avatarMode==='google'&&p.photoURL)return p.photoURL;if(p.avatarMode==='none')return'assets/avatars/sem-foto.svg';return`assets/avatars/${p.avatarId||'pergaminho'}.svg`}
function borderSrc(id){return`assets/borders/${id||'simples'}.svg`}
async function ensureProfile(user){const ref=doc(db,'users',user.uid);const snap=await getDoc(ref);const base={uid:user.uid,email:user.email||'',displayName:user.displayName||'Jovem na Palavra',photoURL:user.photoURL||'',avatarMode:user.photoURL?'google':'preset',avatarId:'pergaminho',borderId:'simples',activeTitle:'Novo Discípulo',privacy:'public',points:0,weeklyPoints:0,monthlyPoints:0,xp:0,level:1,answered:0,correct:0,competitiveWins:0,createdAt:serverTimestamp(),lastDaily:todayKey(),lastWeek:weekKey(),lastMonth:monthKey(),stats:{},unlocks:{titles:['Novo Discípulo'],borders:['simples'],avatars:['pergaminho','sem-foto']}};if(!snap.exists()){await setDoc(ref,base);return base}let data=snap.data();const upd={};if(data.lastDaily!==todayKey())Object.assign(upd,{lastDaily:todayKey(),answeredToday:0,correctToday:0});if(data.lastWeek!==weekKey())Object.assign(upd,{lastWeek:weekKey(),weeklyPoints:0,answeredWeek:0,hardCorrectWeek:0});if(data.lastMonth!==monthKey())Object.assign(upd,{lastMonth:monthKey(),monthlyPoints:0});if(Object.keys(upd).length){await updateDoc(ref,upd);data={...data,...upd}}return {...base,...data}}
async function checkAdmin(uid){const snap=await getDoc(doc(db,'admins',uid)).catch(()=>null);isAdmin=!!snap?.exists();$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin))}
function renderAuth(){const a=$('#authArea');if(!currentUser){a.innerHTML='';return}a.innerHTML=`<div class="auth-pill"><img src="${avatarSrc()}"><span>${profile?.displayName||'Usuário'}</span><button class="text-btn" id="logoutBtn">Sair</button></div>`;$('#logoutBtn').onclick=()=>signOut(auth)}
function setView(v){$$('.view').forEach(x=>x.classList.remove('active'));$(`#${v}View`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={home:['Bem-vindo','Jovens na Palavra'],solo:['Quiz','Quiz Solo'],study:['Revisão','Estudo dos Erros'],journey:['Jornada','Livros da Bíblia'],room:['Competitivo','Desafio entre Irmãos'],tournaments:['Eventos','Campeonatos'],missions:['Progresso','Missões'],ranking:['Classificação','Ranking'],friends:['Comunhão','Amigos'],profile:['Conta','Perfil'],admin:['Admin','Painel Administrativo']};$('#viewEyebrow').textContent=titles[v]?.[0]||'';$('#viewTitle').textContent=titles[v]?.[1]||'';if(v==='ranking')loadRanking();if(v==='friends')loadFriends();if(v==='study')renderReview();if(v==='tournaments')loadTournaments();$('#sidebar').classList.remove('open')}
function renderStats(){if(!profile)return;$('#welcomeName').textContent=`Paz de Deus, ${profile.displayName||'jovem'}!`;$('#statPoints').textContent=profile.points||0;$('#statLevel').textContent=profile.level||1;$('#statXp').textContent=(profile.xp||0)+' XP';$('#statAnswered').textContent=(profile.answered||0)+' perguntas';$('#statAccuracy').textContent=profile.answered?Math.round(profile.correct/profile.answered*100)+'%':'0%'}
function progressVal(m){return Math.min(100,Math.round(((profile?.[m.key]||0)/m.target)*100))}
function renderMissions(){const html=MISSIONS.map(m=>`<div class="mission"><div class="mission-top"><div><strong>${m.name}</strong><small class="muted">${m.type} • recompensa ${m.reward} XP</small></div><b>${profile?.[m.key]||0}/${m.target}</b></div><div class="progress"><i style="width:${progressVal(m)}%"></i></div></div>`).join('');$('#homeMissions').innerHTML=html;$('#missionsList').innerHTML=html}
function renderAchievements(){const items=[['Bronze','Responda 50 perguntas',profile?.answered||0,50],['Ouro','Acerte 100 perguntas',profile?.correct||0,100],['Mestre','Alcance 5000 XP',profile?.xp||0,5000],['Competidor','Vença 10 desafios',profile?.competitiveWins||0,10]];$('#achievementStrip').innerHTML=items.map(i=>`<div class="mission"><strong>${i[0]}</strong><small class="muted">${i[1]}</small><div class="progress"><i style="width:${Math.min(100,Math.round(i[2]/i[3]*100))}%"></i></div></div>`).join('')}
function renderBooks(){const groups={};QUESTION_BANK.forEach(q=>{groups[q.book]=groups[q.book]||{book:q.book,testament:q.testament,count:0};groups[q.book].count++});$('#bookGrid').innerHTML=Object.values(groups).map(b=>`<button class="book-card" data-book="${b.book}"><strong>${b.book}</strong><small class="muted">${b.testament} • ${b.count} perguntas</small></button>`).join('');$$('[data-book]').forEach(b=>b.onclick=()=>{$('#soloCategory').value='all';$('#soloTestament').value='all';setView('solo');startQuiz({book:b.dataset.book,count:10})})}
function renderProfile(){selectedAvatar=profile.avatarId||'pergaminho';selectedBorder=profile.borderId||'simples';selectedTitle=profile.activeTitle||'Novo Discípulo';$('#profileAvatar').src=avatarSrc();$('#profileBorder').src=borderSrc(selectedBorder);$('#profileName').textContent=profile.displayName;$('#profileTitle').textContent=selectedTitle;$('#profileMeta').textContent=`Nível ${profile.level||1} • ${profile.points||0} pontos`;$('#profileNameInput').value=profile.displayName||'';$('#privacyMode').value=profile.privacy||'public';$('#avatarMode').value=profile.avatarMode||'preset';$('#avatarChoices').innerHTML=AVATARS.map(a=>`<button class="choice ${a===selectedAvatar?'active':''}" data-avatar="${a}"><img src="assets/avatars/${a}.svg"><span>${a}</span></button>`).join('');$('#borderChoices').innerHTML=BORDERS.map(b=>`<button class="choice ${b===selectedBorder?'active':''}" data-border="${b}"><img src="assets/borders/${b}.svg"><span>${b}</span></button>`).join('');$('#titleChoices').innerHTML=TITLES.map(t=>`<button class="choice ${t===selectedTitle?'active':''}" data-title="${t}">${t}</button>`).join('');$$('[data-avatar]').forEach(b=>b.onclick=()=>{selectedAvatar=b.dataset.avatar;profile.avatarMode='preset';profile.avatarId=selectedAvatar;renderProfile()});$$('[data-border]').forEach(b=>b.onclick=()=>{selectedBorder=b.dataset.border;profile.borderId=selectedBorder;renderProfile()});$$('[data-title]').forEach(b=>b.onclick=()=>{selectedTitle=b.dataset.title;profile.activeTitle=selectedTitle;renderProfile()})}
function pool(filter={}){let p=QUESTION_BANK.filter(q=>q.active!==false);if(filter.testament&&filter.testament!=='all')p=p.filter(q=>q.testament===filter.testament);if(filter.difficulty&&filter.difficulty!=='all')p=p.filter(q=>q.difficulty===filter.difficulty);if(filter.category&&filter.category!=='all')p=p.filter(q=>q.category===filter.category);if(filter.book)p=p.filter(q=>q.book===filter.book);return p.sort(()=>Math.random()-.5).slice(0,Number(filter.count||5))}
function startQuiz(over={}){const qs=pool({testament:$('#soloTestament').value,difficulty:$('#soloDifficulty').value,category:$('#soloCategory').value,count:$('#soloCount').value,...over});if(!qs.length)return toast('Não há perguntas nesse filtro.');quiz={qs,index:0,correct:0,points:0,wrong:[],started:Date.now(),answered:false};renderQuestion()}
function renderQuestion(){const q=quiz.qs[quiz.index];$('#quizStage').innerHTML=`<div class="question-card"><div class="quiz-meta"><span>Pergunta ${quiz.index+1}/${quiz.qs.length}</span><span>${q.testament} • ${q.book} • ${q.difficulty.toUpperCase()}</span><span class="timer" id="qTimer">--</span></div><h3 class="question-text">${q.question}</h3><div class="option-grid">${q.options.map(o=>`<button class="option-btn" data-option="${o.replaceAll('"','&quot;')}">${o}</button>`).join('')}</div><div id="feedbackBox"></div></div>`;$$('.option-btn').forEach(b=>b.onclick=()=>answerQuestion(b.dataset.option));}
async function answerQuestion(choice){if(!quiz||quiz.answered)return;quiz.answered=true;const q=quiz.qs[quiz.index];const right=choice===q.answer;$$('.option-btn').forEach(b=>{b.disabled=true;if(b.dataset.option===q.answer)b.classList.add('correct');if(b.dataset.option===choice&&!right)b.classList.add('wrong')});if(right){quiz.correct++;quiz.points+=pointsFor(q)}else{quiz.wrong.push(q);saveReview(q)}$('#feedbackBox').innerHTML=`<div class="feedback"><b>${right?'Resposta correta!':'Resposta incorreta.'}</b><p>Resposta correta: <strong>${q.answer}</strong></p><p>Referência JFA: <strong>${q.reference}</strong></p>${q.verseText?`<p><em>Trecho:</em> “${q.verseText}”</p>`:''}<p>${q.explanation}</p><div class="actions"><button class="primary" id="nextQuestionBtn">${quiz.index+1<quiz.qs.length?'Próxima':'Finalizar'}</button><button class="secondary" id="reportBtn">Reportar pergunta</button></div></div>`;$('#nextQuestionBtn').onclick=finishOrNext;$('#reportBtn').onclick=()=>reportQuestion(q)}
function saveReview(q){const arr=JSON.parse(localStorage.getItem('reviewBank')||'[]').filter(x=>x.id!==q.id);arr.unshift(q);localStorage.setItem('reviewBank',JSON.stringify(arr.slice(0,80)))}
function renderReview(){const arr=JSON.parse(localStorage.getItem('reviewBank')||'[]');$('#reviewList').innerHTML=arr.map(q=>`<div class="card"><strong>${q.question}</strong><p class="muted">Resposta: ${q.answer} • ${q.reference}</p><p>${q.explanation}</p></div>`).join('')||'<p class="muted">Você ainda não tem perguntas para revisar.</p>'}
async function reportQuestion(q){if(!currentUser)return;await addDoc(collection(db,'questionReports'),{questionId:q.id,question:q.question,reference:q.reference,userId:currentUser.uid,status:'open',createdAt:serverTimestamp()}).catch(()=>null);toast('Reporte enviado para revisão.')}
async function finishOrNext(){if(quiz.index+1<quiz.qs.length){quiz.index++;quiz.answered=false;renderQuestion();return}await addProgress(quiz);$('#quizStage').innerHTML=`<div class="empty-state"><img src="assets/icons/trophy.svg"><h3>Desafio concluído!</h3><p>Acertos: ${quiz.correct}/${quiz.qs.length} • Pontos: ${quiz.points}</p><p>${quiz.wrong.length?'Revise as perguntas erradas na aba Revisão.':'Excelente! Nenhuma pergunta errada.'}</p><button class="primary" id="againBtn">Jogar novamente</button></div>`;$('#againBtn').onclick=()=>startQuiz();quiz=null}
async function addProgress(qz){const hardCorrect=qz.qs.filter(q=>['dificil','extremo'].includes(q.difficulty)&&!qz.wrong.find(w=>w.id===q.id)).length;const xp=qz.points+qz.correct*3;const newXp=(profile.xp||0)+xp;const update={points:increment(qz.points),weeklyPoints:increment(qz.points),monthlyPoints:increment(qz.points),xp:increment(xp),level:levelFor(newXp),answered:increment(qz.qs.length),correct:increment(qz.correct),answeredToday:increment(qz.qs.length),correctToday:increment(qz.correct),answeredWeek:increment(qz.qs.length),hardCorrectWeek:increment(hardCorrect),updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',currentUser.uid),update);profile={...profile,points:(profile.points||0)+qz.points,weeklyPoints:(profile.weeklyPoints||0)+qz.points,monthlyPoints:(profile.monthlyPoints||0)+qz.points,xp:newXp,level:levelFor(newXp),answered:(profile.answered||0)+qz.qs.length,correct:(profile.correct||0)+qz.correct,answeredToday:(profile.answeredToday||0)+qz.qs.length,correctToday:(profile.correctToday||0)+qz.correct,answeredWeek:(profile.answeredWeek||0)+qz.qs.length,hardCorrectWeek:(profile.hardCorrectWeek||0)+hardCorrect};renderAll()}
async function loadRanking(){const field=$('#rankingMode').value;const box=$('#rankingList');box.innerHTML='<p class="muted">Carregando...</p>';const snap=await getDocs(query(collection(db,'users'),where('privacy','==','public'),orderBy(field,'desc'),limit(50))).catch(()=>null);if(!snap)return box.innerHTML='<p class="muted">Não foi possível carregar. Talvez falte índice do Firestore.</p>';let i=0;box.innerHTML=snap.docs.map(d=>{const u=d.data();i++;return`<div class="ranking-row"><div class="rank-left"><span class="rank-num">${i}</span><img src="${avatarSrc(u)}"><div><strong>${u.displayName||'Usuário'}</strong><small class="muted">${u.activeTitle||'Novo Discípulo'} • Nível ${u.level||1}</small></div></div><b>${u[field]||0} pts</b></div>`}).join('')||'<p class="muted">Sem usuários públicos ainda.</p>'}
async function createRoom(){const qs=pool({testament:$('#roomTestament').value,difficulty:$('#roomDifficulty').value,count:$('#roomQuestions').value});const code='JFA-'+Math.random().toString(36).slice(2,6).toUpperCase();const ref=await addDoc(collection(db,'rooms'),{code,name:$('#roomName').value,leaderId:currentUser.uid,leaderName:profile.displayName,status:'lobby',difficulty:$('#roomDifficulty').value,testament:$('#roomTestament').value,questions:Number($('#roomQuestions').value),minutes:Number($('#roomMinutes').value),scoring:$('#roomScoring').value,questionIds:qs.map(q=>q.id),players:[currentUser.uid],playerNames:{[currentUser.uid]:profile.displayName},scores:{[currentUser.uid]:0},createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await updateDoc(doc(db,'users',currentUser.uid),{roomsJoined:increment(1)});watchRoom(ref.id);toast('Sala criada: '+code)}
async function joinRoom(){const code=$('#joinCode').value.trim().toUpperCase();const snap=await getDocs(query(collection(db,'rooms'),where('code','==',code),limit(1)));if(snap.empty)return toast('Sala não encontrada.');await updateDoc(snap.docs[0].ref,{players:arrayUnion(currentUser.uid),[`playerNames.${currentUser.uid}`]:profile.displayName,[`scores.${currentUser.uid}`]:0,updatedAt:serverTimestamp()});watchRoom(snap.docs[0].id);toast('Você entrou na sala.')}
function watchRoom(id){if(roomUnsub)roomUnsub();roomUnsub=onSnapshot(doc(db,'rooms',id),snap=>{if(!snap.exists())return;const r=snap.data(),isLeader=r.leaderId===currentUser.uid;$('#currentRoomBox').innerHTML=`<p><strong>${r.name}</strong></p><p>Código: <code>${r.code}</code></p><p>${(r.players||[]).length} jogador(es) • ${r.questions} perguntas • ${r.minutes} min</p><p>Líder: ${r.leaderName}</p><div class="card-list">${Object.entries(r.playerNames||{}).map(([uid,n])=>`<div class="friend-row"><span>${n}</span><b>${r.scores?.[uid]||0} pts</b></div>`).join('')}</div><div class="actions">${isLeader?'<button class="primary" id="startRoomMatch">Iniciar partida</button><button class="danger" id="closeRoom">Fechar grupo</button>':'<span class="pill">Aguardando o líder</span>'}</div>`;if($('#startRoomMatch'))$('#startRoomMatch').onclick=()=>updateDoc(doc(db,'rooms',id),{status:'playing',startedAt:Date.now(),updatedAt:serverTimestamp()});if($('#closeRoom'))$('#closeRoom').onclick=()=>updateDoc(doc(db,'rooms',id),{status:'closed',updatedAt:serverTimestamp()})})}
async function sendFriend(){const email=$('#friendEmail').value.trim().toLowerCase();if(!email)return toast('Informe o e-mail.');const snap=await getDocs(query(collection(db,'users'),where('email','==',email),limit(1)));if(snap.empty)return toast('Usuário não encontrado.');const target=snap.docs[0].data();await addDoc(collection(db,'friendRequests'),{from:currentUser.uid,fromName:profile.displayName,fromEmail:profile.email,to:target.uid,toEmail:target.email,status:'pending',createdAt:serverTimestamp()});await updateDoc(doc(db,'users',currentUser.uid),{friendInvites:increment(1)});toast('Convite enviado.');loadFriends()}
async function loadFriends(){const box=$('#friendsList');box.innerHTML='<p class="muted">Carregando...</p>';const sent=await getDocs(query(collection(db,'friendRequests'),where('from','==',currentUser.uid),limit(30))).catch(()=>null);const rec=await getDocs(query(collection(db,'friendRequests'),where('to','==',currentUser.uid),limit(30))).catch(()=>null);let rows=[];sent?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${f.toEmail}</strong><small class="muted">Enviado</small></div><span class="pill">${f.status}</span></div>`)});rec?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${f.fromName}</strong><small class="muted">${f.fromEmail}</small></div><button class="secondary" data-accept="${d.id}">Aceitar</button></div>`)});box.innerHTML=rows.join('')||'<p class="muted">Nenhum convite.</p>';$$('[data-accept]').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'friendRequests',b.dataset.accept),{status:'accepted',acceptedAt:serverTimestamp()});toast('Amizade aceita.');loadFriends()})}
async function loadTournaments(){const box=$('#tournamentList');const snap=await getDocs(query(collection(db,'tournaments'),orderBy('createdAt','desc'),limit(20))).catch(()=>null);box.innerHTML=snap?.docs.map(d=>{const t=d.data();return`<div class="card"><strong>${t.name}</strong><p class="muted">Tema: ${t.theme} • ${t.status}</p><button class="secondary" data-join-t="${d.id}">Participar</button></div>`}).join('')||'<p class="muted">Nenhum campeonato criado ainda.</p>'}
async function createTournament(){await addDoc(collection(db,'tournaments'),{name:'Campeonato da Semana da Mocidade',theme:'Evangelhos e Atos',status:'open',createdBy:currentUser.uid,participants:[currentUser.uid],createdAt:serverTimestamp()});toast('Campeonato criado.');loadTournaments()}
async function syncQuestions(){if(!isAdmin)return toast('Apenas admin.');const batchSize=450;for(let i=0;i<QUESTION_BANK.length;i+=batchSize){const batch=writeBatch(db);QUESTION_BANK.slice(i,i+batchSize).forEach(q=>batch.set(doc(db,'questions',q.id),q));await batch.commit()}toast('1000 perguntas sincronizadas no Firestore.')}
async function addAdminQuestion(){try{const q=JSON.parse($('#adminQuestionJson').value);q.id=q.id||('custom-'+Date.now());q.active=true;q.version=q.version||'JFA';await setDoc(doc(db,'questions',q.id),q);toast('Pergunta adicionada.')}catch(e){toast('JSON inválido.')}}
async function loadReports(){const snap=await getDocs(query(collection(db,'questionReports'),where('status','==','open'),limit(50))).catch(()=>null);$('#adminReports').innerHTML=snap?.docs.map(d=>{const r=d.data();return`<div class="card"><strong>${r.questionId}</strong><p>${r.question}</p><small class="muted">${r.reference}</small></div>`}).join('')||'<p class="muted">Sem reportes abertos.</p>'}
function renderAll(){renderAuth();renderStats();renderMissions();renderAchievements();renderBooks();renderProfile()}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#showEmailLoginBtn').onclick=()=>$('#emailForm').classList.toggle('hidden');$('#googleLoginBtn').onclick=()=>signInWithPopup(auth,provider).catch(e=>toast(e.message));$('#emailSignUpBtn').onclick=async()=>{try{const c=await createUserWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value);if($('#displayNameInput').value)await updateProfile(c.user,{displayName:$('#displayNameInput').value})}catch(e){$('#authMessage').textContent=e.message}};$('#emailSignInBtn').onclick=()=>signInWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value).catch(e=>$('#authMessage').textContent=e.message);$('#startSoloBtn').onclick=()=>startQuiz();$('#clearReviewBtn').onclick=()=>{localStorage.removeItem('reviewBank');renderReview()};$('#refreshRankingBtn').onclick=loadRanking;$('#rankingMode').onchange=loadRanking;$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#sendFriendBtn').onclick=sendFriend;$('#createTournamentBtn').onclick=createTournament;$('#syncQuestionsBtn').onclick=syncQuestions;$('#addQuestionBtn').onclick=addAdminQuestion;$('#loadReportsBtn').onclick=loadReports;$('#saveProfileBtn').onclick=async()=>{const data={displayName:$('#profileNameInput').value||profile.displayName,privacy:$('#privacyMode').value,avatarMode:$('#avatarMode').value,avatarId:selectedAvatar,borderId:selectedBorder,activeTitle:selectedTitle,updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',currentUser.uid),data);profile={...profile,...data};toast('Perfil salvo.');renderAll()};$('#avatarMode').onchange=()=>{profile.avatarMode=$('#avatarMode').value;renderProfile()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('/src/js/sw.js').catch(()=>{});
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){profile=null;$('#authGate').classList.remove('hidden');$('#appContent').classList.add('hidden');renderAuth();return}profile=await ensureProfile(user);await checkAdmin(user.uid);$('#authGate').classList.add('hidden');$('#appContent').classList.remove('hidden');renderAll();setView('home')});
