import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getAnalytics, isSupported } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-analytics.js";
import { getAuth, GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, signOut, onAuthStateChanged, updateProfile } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, addDoc, query, where, orderBy, limit, getDocs, serverTimestamp, increment, arrayUnion, onSnapshot } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyCNnyzZwuBasb_VhUmTXAWMxzOVMlg_LiA",
  authDomain: "projetos-klar.firebaseapp.com",
  projectId: "projetos-klar",
  storageBucket: "projetos-klar.firebasestorage.app",
  messagingSenderId: "484849594276",
  appId: "1:484849594276:web:f1e0a47beaba97cfecdb31",
  measurementId: "G-JEZ2GJKYED"
};

const app = initializeApp(firebaseConfig);
isSupported().then(ok => ok && getAnalytics(app)).catch(() => {});
const auth = getAuth(app);
const db = getFirestore(app);
const provider = new GoogleAuthProvider();

const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => [...document.querySelectorAll(sel)];
const toast = (msg) => { const el = $('#toast'); el.textContent = msg; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3200); };

const AVATARS = [
  ['pergaminho','Pergaminho','assets/avatars/pergaminho.svg'],['cordeiro','Cordeiro','assets/avatars/cordeiro.svg'],['leao','Leão','assets/avatars/leao.svg'],['pomba','Pomba','assets/avatars/pomba.svg'],['peixe','Peixe','assets/avatars/peixe.svg'],['lampada','Lâmpada','assets/avatars/lampada.svg'],['coroa','Coroa','assets/avatars/coroa.svg'],['harpa','Harpa','assets/avatars/harpa.svg'],['barco','Barco','assets/avatars/barco.svg'],['oliveira','Oliveira','assets/avatars/oliveira.svg'],['escudo','Escudo','assets/avatars/escudo.svg'],['trombeta','Trombeta','assets/avatars/trombeta.svg']
];
const BORDERS = [
  ['simples','Simples','assets/borders/simples.svg',0],['bronze','Bronze','assets/borders/bronze.svg',2],['prata','Prata','assets/borders/prata.svg',5],['ouro','Ouro','assets/borders/ouro.svg',10],['azul','Aliança','assets/borders/azul.svg',15],['pomba','Pomba','assets/borders/pomba.svg',20],['fogo','Fogo','assets/borders/fogo.svg',25],['coroa','Coroa','assets/borders/coroa.svg',30],['oliveira','Oliveira','assets/borders/oliveira.svg',35],['apocalipse','Apocalipse','assets/borders/apocalipse.svg',45]
];
const TITLES = [
  ['novo-discipulo','Novo Discípulo',0],['aprendiz','Aprendiz da Palavra',2],['leitor','Leitor Fiel',5],['servo','Servo Atento',8],['evangelhos','Conhecedor dos Evangelhos',12],['cartas','Estudante das Cartas',18],['atos','Testemunha de Atos',24],['sabio','Sábio das Escrituras',32],['mestre','Mestre Bíblico',45],['guardiao','Guardião da Palavra',60]
];
const BOOKS_AT = ['Gênesis','Êxodo','Levítico','Números','Deuteronômio','Josué','Juízes','Rute','1 Samuel','2 Samuel','1 Reis','2 Reis','Salmos','Provérbios','Isaías','Jeremias','Daniel','Jonas','Malaquias'];
const BOOKS_NT = ['Mateus','Marcos','Lucas','João','Atos','Romanos','1 Coríntios','2 Coríntios','Gálatas','Efésios','Filipenses','Colossenses','Hebreus','Tiago','1 Pedro','1 João','Apocalipse'];
const MISSIONS = [
  {id:'daily-5',name:'Responder 5 perguntas hoje',target:5,type:'answered'},
  {id:'daily-3-correct',name:'Acertar 3 perguntas hoje',target:3,type:'correct'},
  {id:'streak-5',name:'Conseguir sequência de 5 acertos',target:5,type:'streak'},
  {id:'play-room',name:'Criar ou entrar em um Desafio entre Irmãos',target:1,type:'room'},
  {id:'friend-1',name:'Enviar 1 convite de amizade',target:1,type:'friend'}
];
const QUESTIONS = [
 {id:'q1',testament:'AT',book:'Gênesis',difficulty:'facil',q:'Quem construiu a arca antes do dilúvio?',options:['Abraão','Noé','Moisés','Elias'],answer:'Noé',ref:'Gênesis 6:13-22',ex:'Noé obedeceu à ordem de Deus e preparou a arca conforme lhe foi mandado.'},
 {id:'q2',testament:'AT',book:'Êxodo',difficulty:'facil',q:'Quem foi chamado para conduzir Israel para fora do Egito?',options:['Josué','Moisés','Samuel','Davi'],answer:'Moisés',ref:'Êxodo 3:10',ex:'Deus chamou Moisés para tirar os filhos de Israel do Egito.'},
 {id:'q3',testament:'AT',book:'1 Samuel',difficulty:'medio',q:'Quem derrotou Golias?',options:['Saul','Jônatas','Davi','Sansão'],answer:'Davi',ref:'1 Samuel 17:49-50',ex:'Davi venceu Golias confiando no Senhor, usando uma pedra e uma funda.'},
 {id:'q4',testament:'AT',book:'Daniel',difficulty:'medio',q:'Quem foi lançado na cova dos leões?',options:['Daniel','José','Ezequiel','Neemias'],answer:'Daniel',ref:'Daniel 6:16-22',ex:'Daniel permaneceu fiel em oração, e Deus o livrou dos leões.'},
 {id:'q5',testament:'AT',book:'Rute',difficulty:'dificil',q:'Qual mulher disse: “O teu povo é o meu povo, o teu Deus é o meu Deus”?',options:['Ester','Rute','Débora','Ana'],answer:'Rute',ref:'Rute 1:16',ex:'Rute demonstrou fidelidade ao acompanhar Noemi.'},
 {id:'q6',testament:'AT',book:'2 Reis',difficulty:'extremo',q:'Qual profeta sucedeu Elias e pediu porção dobrada do seu espírito?',options:['Eliseu','Isaías','Jeremias','Miqueias'],answer:'Eliseu',ref:'2 Reis 2:9-15',ex:'Eliseu recebeu o ministério profético após Elias ser tomado.'},
 {id:'q7',testament:'NT',book:'Mateus',difficulty:'facil',q:'Quem batizou Jesus no rio Jordão?',options:['Pedro','João Batista','Tiago','Filipe'],answer:'João Batista',ref:'Mateus 3:13-17',ex:'Jesus veio até João para ser batizado, e o Espírito de Deus desceu sobre Ele.'},
 {id:'q8',testament:'NT',book:'João',difficulty:'facil',q:'Quem disse: “Eu sou o caminho, e a verdade e a vida”?',options:['Paulo','Pedro','Jesus','João Batista'],answer:'Jesus',ref:'João 14:6',ex:'Jesus ensinou que ninguém vai ao Pai senão por Ele.'},
 {id:'q9',testament:'NT',book:'Lucas',difficulty:'medio',q:'Qual era o nome da mãe de João Batista?',options:['Maria','Isabel','Marta','Ana'],answer:'Isabel',ref:'Lucas 1:5-13',ex:'Isabel, esposa de Zacarias, foi mãe de João Batista.'},
 {id:'q10',testament:'NT',book:'Atos',difficulty:'medio',q:'Quem foi o primeiro mártir cristão mencionado em Atos?',options:['Estevão','Tiago','Pedro','Barnabé'],answer:'Estevão',ref:'Atos 7:54-60',ex:'Estevão foi apedrejado após testemunhar com firmeza.'},
 {id:'q11',testament:'NT',book:'Atos',difficulty:'dificil',q:'Qual mulher vendedora de púrpura ouviu Paulo em Filipos?',options:['Priscila','Lídia','Febe','Dorcas'],answer:'Lídia',ref:'Atos 16:14-15',ex:'Lídia teve o coração aberto para atender às coisas que Paulo dizia.'},
 {id:'q12',testament:'NT',book:'Romanos',difficulty:'dificil',q:'Em qual carta Paulo ensina que “o justo viverá da fé”?',options:['Romanos','Efésios','Colossenses','Filemom'],answer:'Romanos',ref:'Romanos 1:17',ex:'Paulo apresenta a justiça de Deus pela fé.'},
 {id:'q13',testament:'NT',book:'Apocalipse',difficulty:'extremo',q:'À igreja de qual cidade foi dito: “Sê fiel até à morte”?',options:['Éfeso','Esmirna','Laodiceia','Sardes'],answer:'Esmirna',ref:'Apocalipse 2:10',ex:'A mensagem à igreja em Esmirna exorta fidelidade em meio à tribulação.'},
 {id:'q14',testament:'AT',book:'Jonas',difficulty:'facil',q:'Qual profeta fugiu da ordem de ir a Nínive?',options:['Jonas','Amós','Oseias','Habacuque'],answer:'Jonas',ref:'Jonas 1:1-3',ex:'Jonas tentou fugir da presença do Senhor, mas Deus o conduziu ao propósito.'},
 {id:'q15',testament:'AT',book:'Ester',difficulty:'medio',q:'Qual rainha intercedeu pelo seu povo diante do rei?',options:['Vasti','Ester','Mical','Abigail'],answer:'Ester',ref:'Ester 4:14-16',ex:'Ester colocou-se em risco para interceder pelo povo judeu.'},
 {id:'q16',testament:'NT',book:'João',difficulty:'medio',q:'Em qual cidade Jesus transformou água em vinho?',options:['Belém','Caná da Galileia','Jericó','Betânia'],answer:'Caná da Galileia',ref:'João 2:1-11',ex:'Esse sinal manifestou a glória de Jesus aos discípulos.'},
 {id:'q17',testament:'NT',book:'Mateus',difficulty:'dificil',q:'Na parábola das dez virgens, quantas eram prudentes?',options:['Três','Cinco','Sete','Dez'],answer:'Cinco',ref:'Mateus 25:1-13',ex:'Cinco eram prudentes e levaram azeite em suas vasilhas.'},
 {id:'q18',testament:'AT',book:'Provérbios',difficulty:'dificil',q:'Segundo Provérbios, o temor do Senhor é o princípio de quê?',options:['Da riqueza','Da sabedoria','Da força','Da honra'],answer:'Da sabedoria',ref:'Provérbios 9:10',ex:'A verdadeira sabedoria começa no temor reverente ao Senhor.'},
 {id:'q19',testament:'NT',book:'1 Coríntios',difficulty:'extremo',q:'Qual capítulo de 1 Coríntios é conhecido por ensinar profundamente sobre o amor?',options:['11','12','13','15'],answer:'13',ref:'1 Coríntios 13',ex:'Paulo mostra a excelência do amor acima de dons sem caridade.'},
 {id:'q20',testament:'AT',book:'Malaquias',difficulty:'extremo',q:'Qual profeta encerra o Antigo Testamento na ordem bíblica tradicional?',options:['Zacarias','Malaquias','Ageu','Sofonias'],answer:'Malaquias',ref:'Malaquias 4',ex:'Malaquias é o último livro do Antigo Testamento na organização comum da Bíblia.'}
];

let currentUser = null;
let profile = null;
let selectedAvatar = 'pergaminho';
let selectedBorder = 'simples';
let selectedTitle = 'Novo Discípulo';
let quizState = null;
let roomUnsub = null;

function baseProfile(user){return {uid:user.uid,email:user.email||'',displayName:user.displayName||'Irmão(ã)',photoURL:user.photoURL||'',avatarMode:user.photoURL?'google':'preset',avatarId:'pergaminho',borderId:'simples',activeTitle:'Novo Discípulo',points:0,xp:0,level:1,answered:0,correct:0,bestStreak:0,currentStreak:0,roomsPlayed:0,friendsSent:0,unlockedTitles:['Novo Discípulo'],unlockedBorders:['simples'],createdAt:serverTimestamp(),updatedAt:serverTimestamp()};}
async function ensureProfile(user){const ref=doc(db,'users',user.uid);const snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,baseProfile(user));return baseProfile(user);}return snap.data();}
function getAvatarSrc(p=profile){if(!p)return 'assets/avatars/pergaminho.svg'; if(p.avatarMode==='none')return 'assets/avatars/sem-foto.svg'; if(p.avatarMode==='google'&&p.photoURL)return p.photoURL; return (AVATARS.find(a=>a[0]===p.avatarId)?.[2])||'assets/avatars/pergaminho.svg';}
function getBorderSrc(id){return (BORDERS.find(b=>b[0]===id)?.[2])||'assets/borders/simples.svg';}
function unlockedLevelItems(level){return {borders:BORDERS.filter(b=>level>=b[3]).map(b=>b[0]),titles:TITLES.filter(t=>level>=t[2]).map(t=>t[1])};}
async function refreshUnlocks(){if(!profile)return;const unlocked=unlockedLevelItems(profile.level||1);profile.unlockedBorders=[...new Set([...(profile.unlockedBorders||[]),...unlocked.borders])];profile.unlockedTitles=[...new Set([...(profile.unlockedTitles||[]),...unlocked.titles])];await updateDoc(doc(db,'users',currentUser.uid),{unlockedBorders:profile.unlockedBorders,unlockedTitles:profile.unlockedTitles,updatedAt:serverTimestamp()}).catch(()=>{});}
function calcLevel(xp){return Math.max(1,Math.floor(Math.sqrt((xp||0)/90))+1);}
async function addProgress({answered=0,correct=0,points=0,room=0,friend=0,streak=0}){if(!currentUser)return;const newXp=(profile.xp||0)+points;const newLevel=calcLevel(newXp);const newBest=Math.max(profile.bestStreak||0,streak||profile.currentStreak||0);await updateDoc(doc(db,'users',currentUser.uid),{answered:increment(answered),correct:increment(correct),points:increment(points),xp:increment(points),level:newLevel,bestStreak:newBest,roomsPlayed:increment(room),friendsSent:increment(friend),updatedAt:serverTimestamp()});profile={...profile,answered:(profile.answered||0)+answered,correct:(profile.correct||0)+correct,points:(profile.points||0)+points,xp:newXp,level:newLevel,bestStreak:newBest,roomsPlayed:(profile.roomsPlayed||0)+room,friendsSent:(profile.friendsSent||0)+friend};await refreshUnlocks();renderAll();}

function setView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={home:['Bem-vindo','Jovens na Palavra'],solo:['Quiz Solo','Desafio Bíblico'],journey:['Jornada','Livros da Bíblia'],room:['Competição','Desafio entre Irmãos'],missions:['Progresso','Missões'],ranking:['Global','Classificação'],friends:['Comunhão','Amigos'],profile:['Conta','Perfil']};$('#viewEyebrow').textContent=titles[view]?.[0]||'';$('#viewTitle').textContent=titles[view]?.[1]||'';$('#sidebar').classList.remove('open');if(view==='ranking')loadRanking();if(view==='friends')loadFriends();}
function renderAuth(){const a=$('#authArea');if(!currentUser){a.innerHTML='';return;}a.innerHTML=`<div class="user-pill"><img src="${getAvatarSrc()}" alt=""><span>${profile?.displayName||currentUser.displayName||'Usuário'}</span></div><button class="secondary" id="logoutBtn">Sair</button>`;$('#logoutBtn').onclick=()=>signOut(auth);}
function renderStats(){if(!profile)return;$('#welcomeName').textContent=`Vamos estudar, ${profile.displayName||'irmão(ã)'}?`;$('#statPoints').textContent=profile.points||0;$('#statLevel').textContent=profile.level||1;$('#statXp').textContent=`${profile.xp||0} XP`;$('#statAnswered').textContent=`${profile.answered||0} perguntas`;$('#statAccuracy').textContent=`${profile.answered?Math.round((profile.correct||0)/(profile.answered||1)*100):0}%`;}
function missionProgress(m){if(!profile)return 0;if(m.type==='answered')return profile.answered||0;if(m.type==='correct')return profile.correct||0;if(m.type==='streak')return profile.bestStreak||0;if(m.type==='room')return profile.roomsPlayed||0;if(m.type==='friend')return profile.friendsSent||0;return 0;}
function renderMissions(){const html=MISSIONS.map(m=>{const val=Math.min(missionProgress(m),m.target);const pct=Math.round(val/m.target*100);return `<div class="mission"><div><strong>${m.name}</strong><small>${val}/${m.target}</small><div class="progress"><span style="width:${pct}%"></span></div></div><b>${pct>=100?'Concluída':'Em progresso'}</b></div>`}).join('');$('#homeMissions').innerHTML=html;$('#missionsList').innerHTML=html+`<div class="mission"><div><strong>Semana da Mocidade</strong><small>Vença 5 desafios entre irmãos para liberar uma moldura especial.</small><div class="progress"><span style="width:${Math.min((profile?.roomsPlayed||0)/5*100,100)}%"></span></div></div><b>Semanal</b></div>`;}
function renderAchievements(){const nextB=BORDERS.filter(b=>!(profile?.unlockedBorders||[]).includes(b[0])).slice(0,3);const nextT=TITLES.filter(t=>!(profile?.unlockedTitles||[]).includes(t[1])).slice(0,3);$('#achievementStrip').innerHTML=[...nextB.map(b=>`<div class="achievement"><strong>Moldura ${b[1]}</strong><small>Alcance o nível ${b[3]}</small></div>`),...nextT.map(t=>`<div class="achievement"><strong>${t[1]}</strong><small>Alcance o nível ${t[2]}</small></div>`)].join('')||'<p class="muted">Você já desbloqueou tudo desta versão inicial.</p>';}
function renderBooks(){const card=(b,t)=>`<button class="book-card" data-book="${b}" data-testament="${t}"><strong>${b}</strong><small>${t==='AT'?'Antigo Testamento':'Novo Testamento'}</small></button>`;$('#bookGrid').innerHTML=BOOKS_AT.map(b=>card(b,'AT')).join('')+BOOKS_NT.map(b=>card(b,'NT')).join('');$$('.book-card').forEach(btn=>btn.onclick=()=>{setView('solo');$('#soloTestament').value=btn.dataset.testament;toast(`Jornada de ${btn.dataset.book}: filtre perguntas deste livro nas próximas versões.`);});}
function renderProfile(){if(!profile)return;$('#profileAvatar').src=getAvatarSrc();$('#profileBorder').src=getBorderSrc(profile.borderId||'simples');$('#profileName').textContent=profile.displayName||'Usuário';$('#profileTitle').textContent=profile.activeTitle||'Novo Discípulo';$('#profileEmail').textContent=profile.email||'';$('#profileLevel').textContent=profile.level||1;$('#profilePoints').textContent=profile.points||0;$('#profileStreak').textContent=profile.bestStreak||0;$('#profileNameInput').value=profile.displayName||'';$('#avatarMode').value=profile.avatarMode||'preset';selectedAvatar=profile.avatarId||'pergaminho';selectedBorder=profile.borderId||'simples';selectedTitle=profile.activeTitle||'Novo Discípulo';$('#avatarGrid').innerHTML=AVATARS.map(a=>`<button class="asset-card ${selectedAvatar===a[0]?'active':''}" data-avatar="${a[0]}"><img src="${a[2]}" alt=""><span>${a[1]}</span></button>`).join('')+`<button class="asset-card" data-mode="none"><img src="assets/avatars/sem-foto.svg" alt=""><span>Sem foto</span></button>`;const unlocked=profile.unlockedBorders||['simples'];$('#borderGrid').innerHTML=BORDERS.map(b=>`<button class="asset-card ${selectedBorder===b[0]?'active':''} ${unlocked.includes(b[0])?'':'locked'}" data-border="${b[0]}" ${unlocked.includes(b[0])?'':'disabled'}><img src="${b[2]}" alt=""><span>${b[1]}</span></button>`).join('');const unlockedT=profile.unlockedTitles||['Novo Discípulo'];$('#titleGrid').innerHTML=TITLES.map(t=>`<button class="chip ${selectedTitle===t[1]?'active':''} ${unlockedT.includes(t[1])?'':'locked'}" data-title="${t[1]}" ${unlockedT.includes(t[1])?'':'disabled'}>${t[1]}</button>`).join('');$$('[data-avatar]').forEach(b=>b.onclick=()=>{selectedAvatar=b.dataset.avatar;$('#avatarMode').value='preset';renderProfilePreview();$$('[data-avatar]').forEach(x=>x.classList.toggle('active',x===b));});$$('[data-mode="none"]').forEach(b=>b.onclick=()=>{$('#avatarMode').value='none';renderProfilePreview();});$$('[data-border]').forEach(b=>b.onclick=()=>{selectedBorder=b.dataset.border;renderProfilePreview();$$('[data-border]').forEach(x=>x.classList.toggle('active',x===b));});$$('[data-title]').forEach(b=>b.onclick=()=>{selectedTitle=b.dataset.title;$$('[data-title]').forEach(x=>x.classList.toggle('active',x===b));$('#profileTitle').textContent=selectedTitle;});}
function renderProfilePreview(){const mode=$('#avatarMode').value;let src='assets/avatars/sem-foto.svg';if(mode==='google'&&profile.photoURL)src=profile.photoURL;if(mode==='preset')src=AVATARS.find(a=>a[0]===selectedAvatar)?.[2]||'assets/avatars/pergaminho.svg';$('#profileAvatar').src=src;$('#profileBorder').src=getBorderSrc(selectedBorder);}
function renderAll(){renderAuth();renderStats();renderMissions();renderAchievements();renderBooks();renderProfile();}

function filteredQuestions({testament='all',difficulty='all',count=5}){let pool=QUESTIONS.filter(q=>(testament==='all'||q.testament===testament)&&(difficulty==='all'||q.difficulty===difficulty));pool=[...pool].sort(()=>Math.random()-.5);return pool.slice(0,Number(count));}
function pointsFor(q,fast=false){const base={facil:10,medio:20,dificil:35,extremo:60}[q.difficulty]||15;return base+(fast?5:0);}
function startQuiz(){const qs=filteredQuestions({testament:$('#soloTestament').value,difficulty:$('#soloDifficulty').value,count:$('#soloCount').value});if(!qs.length)return toast('Não há perguntas para esse filtro ainda.');quizState={qs,index:0,correct:0,points:0,streak:0,answered:false};renderQuestion();}
function renderQuestion(){const s=quizState;const q=s.qs[s.index];$('#quizStage').innerHTML=`<div class="question-card"><div class="quiz-meta"><span>Pergunta ${s.index+1}/${s.qs.length}</span><span>${q.testament} • ${q.book} • ${q.difficulty.toUpperCase()}</span></div><h3 class="question-text">${q.q}</h3><div class="option-grid">${q.options.map(o=>`<button class="option-btn" data-option="${o}">${o}</button>`).join('')}</div><div id="feedbackBox"></div></div>`;$$('.option-btn').forEach(b=>b.onclick=()=>answerQuestion(b.dataset.option));}
async function answerQuestion(choice){const s=quizState;if(!s||s.answered)return;s.answered=true;const q=s.qs[s.index];const right=choice===q.answer;$$('.option-btn').forEach(b=>{b.disabled=true;if(b.dataset.option===q.answer)b.classList.add('correct');if(b.dataset.option===choice&&!right)b.classList.add('wrong');});if(right){s.correct++;s.streak++;const pts=pointsFor(q);s.points+=pts;}else{s.streak=0;}$('#feedbackBox').innerHTML=`<div class="feedback"><b>${right?'Resposta correta!':'Resposta incorreta.'}</b><p>Resposta correta: <strong>${q.answer}</strong></p><p>Referência JFA: <strong>${q.ref}</strong></p><p>${q.ex}</p><button class="primary" id="nextQuestionBtn">${s.index+1<s.qs.length?'Próxima pergunta':'Finalizar desafio'}</button></div>`;$('#nextQuestionBtn').onclick=finishOrNext;}
async function finishOrNext(){const s=quizState;if(s.index+1<s.qs.length){s.index++;s.answered=false;renderQuestion();return;}await addProgress({answered:s.qs.length,correct:s.correct,points:s.points,streak:s.streak});$('#quizStage').innerHTML=`<div class="empty-state"><img src="assets/icons/trophy.svg" alt=""><h3>Desafio concluído!</h3><p>Você acertou ${s.correct}/${s.qs.length} e recebeu ${s.points} pontos.</p><button class="primary" id="againBtn">Jogar novamente</button></div>`;$('#againBtn').onclick=startQuiz;quizState=null;}

async function loadRanking(){const list=$('#rankingList');list.innerHTML='<p class="muted">Carregando classificação...</p>';const snap=await getDocs(query(collection(db,'users'),orderBy('points','desc'),limit(30))).catch(()=>null);if(!snap){list.innerHTML='<p class="muted">Não foi possível carregar. Verifique regras/índices do Firestore.</p>';return;}let i=0;list.innerHTML=snap.docs.map(d=>{const u=d.data();i++;const src=u.avatarMode==='google'&&u.photoURL?u.photoURL:(AVATARS.find(a=>a[0]===u.avatarId)?.[2]||'assets/avatars/pergaminho.svg');return `<div class="ranking-row"><div class="rank-left"><span class="rank-num">${i}</span><img src="${src}" alt=""><div><strong>${u.displayName||'Usuário'}</strong><small class="muted">${u.activeTitle||'Novo Discípulo'} • Nível ${u.level||1}</small></div></div><b>${u.points||0} pts</b></div>`;}).join('')||'<p class="muted">Ainda não há usuários na classificação.</p>';}
async function createRoom(){const code='JFA-'+Math.random().toString(36).slice(2,6).toUpperCase();const data={code,name:$('#roomName').value||'Desafio da Mocidade',leaderId:currentUser.uid,leaderName:profile.displayName,status:'lobby',difficulty:$('#roomDifficulty').value,testament:$('#roomTestament').value,questions:Number($('#roomQuestions').value||5),minutes:Number($('#roomMinutes').value||10),scoring:$('#roomScoring').value,players:[currentUser.uid],playerNames:{[currentUser.uid]:profile.displayName},createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const ref=await addDoc(collection(db,'rooms'),data);await addProgress({room:1});watchRoom(ref.id);toast(`Sala criada: ${code}`);}
async function joinRoom(){const code=$('#joinCode').value.trim().toUpperCase();if(!code)return toast('Digite o código da sala.');const snap=await getDocs(query(collection(db,'rooms'),where('code','==',code),limit(1)));if(snap.empty)return toast('Sala não encontrada.');const ref=snap.docs[0].ref;await updateDoc(ref,{players:arrayUnion(currentUser.uid),[`playerNames.${currentUser.uid}`]:profile.displayName,updatedAt:serverTimestamp()});await addProgress({room:1});watchRoom(snap.docs[0].id);toast('Você entrou na sala.');}
function watchRoom(id){if(roomUnsub)roomUnsub();roomUnsub=onSnapshot(doc(db,'rooms',id),(snap)=>{if(!snap.exists())return;const r=snap.data();const isLeader=r.leaderId===currentUser.uid;$('#currentRoomBox').innerHTML=`<p><strong>${r.name}</strong></p><p>Código: <code>${r.code}</code></p><p>${(r.players||[]).length} jogador(es) • ${r.questions} perguntas • ${r.minutes} min</p><p>Líder: ${r.leaderName||'Usuário'}</p><div class="actions">${isLeader?'<button class="primary" id="startRoomMatch">Iniciar partida</button><button class="danger" id="closeRoom">Fechar grupo</button>':'<span class="pill">Aguardando o líder iniciar</span>'}</div>`;if($('#startRoomMatch'))$('#startRoomMatch').onclick=()=>toast('Base pronta. Próximo passo: sincronizar perguntas em tempo real com Cloud Functions.');if($('#closeRoom'))$('#closeRoom').onclick=()=>updateDoc(doc(db,'rooms',id),{status:'closed',updatedAt:serverTimestamp()});});}
async function sendFriend(){const email=$('#friendEmail').value.trim().toLowerCase();if(!email)return toast('Informe o e-mail do usuário.');const snap=await getDocs(query(collection(db,'users'),where('email','==',email),limit(1)));if(snap.empty)return toast('Usuário não encontrado.');const target=snap.docs[0].data();await addDoc(collection(db,'friendRequests'),{from:currentUser.uid,fromName:profile.displayName,fromEmail:profile.email,to:target.uid,toEmail:target.email,status:'pending',createdAt:serverTimestamp()});await addProgress({friend:1});toast('Convite de amizade enviado.');$('#friendEmail').value='';loadFriends();}
async function loadFriends(){const box=$('#friendsList');box.innerHTML='<p class="muted">Carregando...</p>';const sent=await getDocs(query(collection(db,'friendRequests'),where('from','==',currentUser.uid),limit(20))).catch(()=>null);const rec=await getDocs(query(collection(db,'friendRequests'),where('to','==',currentUser.uid),limit(20))).catch(()=>null);const rows=[];sent?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${f.toEmail}</strong><small class="muted">Convite enviado</small></div><span class="pill">${f.status}</span></div>`);});rec?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${f.fromName}</strong><small class="muted">${f.fromEmail}</small></div><span class="pill">Recebido</span></div>`);});box.innerHTML=rows.join('')||'<p class="muted">Nenhum convite ainda.</p>';}

$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#showEmailLoginBtn').onclick=()=>$('#emailForm').classList.toggle('hidden');$('#googleLoginBtn').onclick=()=>signInWithPopup(auth,provider).catch(e=>toast(e.message));$('#emailSignUpBtn').onclick=async()=>{try{const cred=await createUserWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value);if($('#displayNameInput').value)await updateProfile(cred.user,{displayName:$('#displayNameInput').value});}catch(e){$('#authMessage').textContent=e.message;}};$('#emailSignInBtn').onclick=()=>signInWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value).catch(e=>$('#authMessage').textContent=e.message);$('#startSoloBtn').onclick=startQuiz;$('#refreshRankingBtn').onclick=loadRanking;$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#sendFriendBtn').onclick=sendFriend;$('#avatarMode').onchange=renderProfilePreview;$('#saveProfileBtn').onclick=async()=>{const data={displayName:$('#profileNameInput').value||profile.displayName,avatarMode:$('#avatarMode').value,avatarId:selectedAvatar,borderId:selectedBorder,activeTitle:selectedTitle,updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',currentUser.uid),data);profile={...profile,...data};toast('Perfil salvo.');renderAll();};

onAuthStateChanged(auth,async(user)=>{currentUser=user;if(!user){profile=null;$('#authGate').classList.remove('hidden');$('#appContent').classList.add('hidden');renderAuth();return;}profile=await ensureProfile(user);if(user.displayName&&!profile.displayName)profile.displayName=user.displayName;$('#authGate').classList.add('hidden');$('#appContent').classList.remove('hidden');await refreshUnlocks();renderAll();setView('home');});
