import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, createUserWithEmailAndPassword, signInWithEmailAndPassword, updateProfile, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, addDoc, collection, getDocs, query, where, limit, onSnapshot, serverTimestamp, increment, arrayUnion, arrayRemove, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';
import { QUESTION_BANK } from '../data/questions.js';

const firebaseConfig={apiKey:'AIzaSyCNnyzZwuBasb_VhUmTXAWMxzOVMlg_LiA',authDomain:'projetos-klar.firebaseapp.com',projectId:'projetos-klar',storageBucket:'projetos-klar.firebasestorage.app',messagingSenderId:'484849594276',appId:'1:484849594276:web:f1e0a47beaba97cfecdb31',measurementId:'G-JEZ2GJKYED'};
const app=initializeApp(firebaseConfig);const auth=getAuth(app);const provider=new GoogleAuthProvider();const db=getFirestore(app);
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const state={user:null,profile:null,isAdmin:false,route:'home',roomId:null,roomUnsub:null,quiz:null,deferredInstall:null,selectedAvatar:'pergaminho',selectedBorder:'simples',selectedTitle:'Novo Discípulo'};
const AVATARS=['pergaminho','cordeiro','leao','pomba','peixe','lampada','coroa','harpa','barco','oliveira','escudo','trombeta','biblia','estrela','monte','sem-foto','ancora','trigo','agua','sol'];
const BORDERS=['simples','bronze','prata','ouro','azul','pomba','fogo','coroa','oliveira','apocalipse','mestre','celestial'];
const TITLES=['Novo Discípulo','Aprendiz da Palavra','Jovem Bereano','Leitor Fiel','Conhecedor dos Evangelhos','Servo Prudente','Guardião da Palavra','Mensageiro da Fé','Mestre dos Evangelhos','Arauto do Apocalipse','Lenda da Mocidade'];
const BORDER_REQUIREMENTS={simples:['Liberada no início',p=>true],bronze:['Responder 50 perguntas',p=>num(p.answered)>=50],prata:['Responder 150 perguntas',p=>num(p.answered)>=150],ouro:['Acertar 100 perguntas',p=>num(p.correct)>=100],azul:['Alcançar nível 5',p=>num(p.level,1)>=5],pomba:['Alcançar 1000 XP',p=>num(p.xp)>=1000],fogo:['Acertar 20 difíceis/extremas na semana',p=>num(p.hardCorrectWeek)>=20],coroa:['Ter 3000 pontos',p=>num(p.points)>=3000],oliveira:['Participar de 3 salas',p=>num(p.roomsJoined)>=3],apocalipse:['Alcançar nível 20',p=>num(p.level,1)>=20],mestre:['Alcançar 5000 XP',p=>num(p.xp)>=5000],celestial:['Vencer 10 desafios',p=>num(p.competitiveWins)>=10]};
const TITLE_REQUIREMENTS={'Novo Discípulo':['Liberado no início',p=>true],'Aprendiz da Palavra':['Responder 25 perguntas',p=>num(p.answered)>=25],'Jovem Bereano':['Acertar 50 perguntas',p=>num(p.correct)>=50],'Leitor Fiel':['Alcançar 500 XP',p=>num(p.xp)>=500],'Conhecedor dos Evangelhos':['Acertar 120 perguntas',p=>num(p.correct)>=120],'Servo Prudente':['Alcançar nível 8',p=>num(p.level,1)>=8],'Guardião da Palavra':['Ter 2500 pontos',p=>num(p.points)>=2500],'Mensageiro da Fé':['Enviar 3 convites de amizade',p=>num(p.friendInvites)>=3],'Mestre dos Evangelhos':['Alcançar 5000 XP',p=>num(p.xp)>=5000],'Arauto do Apocalipse':['Alcançar nível 20',p=>num(p.level,1)>=20],'Lenda da Mocidade':['Vencer 10 desafios',p=>num(p.competitiveWins)>=10]};
const MISSIONS=[{id:'daily10',type:'Diária',name:'Responder 10 perguntas',target:10,key:'answeredToday',reward:50},{id:'daily5',type:'Diária',name:'Acertar 5 perguntas',target:5,key:'correctToday',reward:40},{id:'weekly100',type:'Semanal',name:'Responder 100 perguntas na semana',target:100,key:'answeredWeek',reward:250},{id:'hard20',type:'Semanal',name:'Acertar 20 difíceis/extremas',target:20,key:'hardCorrectWeek',reward:300},{id:'friend1',type:'Permanente',name:'Enviar um convite de amizade',target:1,key:'friendInvites',reward:80},{id:'room1',type:'Permanente',name:'Participar de uma sala',target:1,key:'roomsJoined',reward:100}];
const categories=[...new Set(QUESTION_BANK.map(q=>q.category).filter(Boolean))].sort();
const books=[...new Map(QUESTION_BANK.map(q=>[q.book,{book:q.book,testament:q.testament,count:0}])).values()];QUESTION_BANK.forEach(q=>{const b=books.find(x=>x.book===q.book);if(b)b.count++});

function num(v,d=0){return Number.isFinite(Number(v))?Number(v):d}function todayKey(){return new Date().toISOString().slice(0,10)}function weekKey(){const d=new Date();const s=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-W'+String(Math.ceil((((d-s)/86400000)+s.getDay()+1)/7)).padStart(2,'0')}function monthKey(){return new Date().toISOString().slice(0,7)}function levelFor(xp){return Math.max(1,Math.floor(Math.sqrt(num(xp)/90))+1)}function pointsFor(q,fast=false){return ({facil:10,medio:20,dificil:35,extremo:60}[q.difficulty]||15)+(fast?5:0)}function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toast').appendChild(el);setTimeout(()=>el.remove(),3600)}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function avatarSrc(p=state.profile){if(!p)return'assets/avatars/pergaminho.svg';if(p.avatarMode==='google'&&p.photoURL)return p.photoURL;if(p.avatarMode==='none')return'assets/avatars/sem-foto.svg';return`assets/avatars/${p.avatarId||'pergaminho'}.svg`}function borderSrc(id){return`assets/borders/${id||'simples'}.svg`}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function isBorderUnlocked(id){return (BORDER_REQUIREMENTS[id]?.[1]||(()=>false))(state.profile||{})}function isTitleUnlocked(t){return (TITLE_REQUIREMENTS[t]?.[1]||(()=>false))(state.profile||{})}

async function ensureProfile(user){const ref=doc(db,'users',user.uid);const snap=await getDoc(ref);const base={uid:user.uid,email:user.email||'',displayName:user.displayName||'Jovem na Palavra',photoURL:user.photoURL||'',avatarMode:user.photoURL?'google':'preset',avatarId:'pergaminho',borderId:'simples',activeTitle:'Novo Discípulo',privacy:'public',points:0,weeklyPoints:0,monthlyPoints:0,xp:0,level:1,answered:0,correct:0,answeredToday:0,correctToday:0,answeredWeek:0,hardCorrectWeek:0,friendInvites:0,roomsJoined:0,competitiveWins:0,lastDaily:todayKey(),lastWeek:weekKey(),lastMonth:monthKey(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()};if(!snap.exists()){await setDoc(ref,base);return {...base,createdAt:null,updatedAt:null}}let data={...base,...snap.data()};const upd={};if(data.lastDaily!==todayKey())Object.assign(upd,{lastDaily:todayKey(),answeredToday:0,correctToday:0});if(data.lastWeek!==weekKey())Object.assign(upd,{lastWeek:weekKey(),weeklyPoints:0,answeredWeek:0,hardCorrectWeek:0});if(data.lastMonth!==monthKey())Object.assign(upd,{lastMonth:monthKey(),monthlyPoints:0});if(data.borderId&&!isUnlockedWithProfile(data.borderId,BORDER_REQUIREMENTS,data))upd.borderId='simples';if(data.activeTitle&&!isUnlockedWithProfile(data.activeTitle,TITLE_REQUIREMENTS,data))upd.activeTitle='Novo Discípulo';if(Object.keys(upd).length){await updateDoc(ref,upd);data={...data,...upd}}return data}
function isUnlockedWithProfile(id,reqMap,p){return (reqMap[id]?.[1]||(()=>false))(p||{})}
async function checkAdmin(uid){const snap=await getDoc(doc(db,'admins',uid)).catch(()=>null);state.isAdmin=!!snap?.exists();$$('.admin-only').forEach(el=>el.classList.toggle('hidden',!state.isAdmin))}
async function refreshProfile(){if(!state.user)return;const snap=await getDoc(doc(db,'users',state.user.uid));if(snap.exists())state.profile={...state.profile,...snap.data()};renderAll()}

function setRoute(route){state.route=route;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${route}View`)?.classList.add('active');$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));const titles={home:['Bem-vindo','Jovens na Palavra'],journey:['Jornada','Livros da Bíblia'],tournaments:['Eventos','Campeonatos'],review:['Revisão','Estudo dos Erros'],missions:['Progresso','Missões'],ranking:['Classificação','Ranking'],friends:['Comunhão','Amigos'],profile:['Conta','Perfil'],admin:['Admin','Painel Administrativo']};$('#viewKicker').textContent=titles[route]?.[0]||'';$('#viewTitle').textContent=titles[route]?.[1]||'';$('#sidebar').classList.remove('open');if(route==='ranking')loadRanking();if(route==='friends')loadFriends();if(route==='tournaments')loadTournaments();if(route==='review')renderReview();if(route==='journey')renderJourney();}
function renderAuth(){const box=$('#authArea');if(!state.user){box.innerHTML='';return}box.innerHTML=`<div class="auth-pill"><img src="${avatarSrc()}" alt=""><span>${esc(state.profile?.displayName||'Usuário')}</span><button class="text-btn" id="logoutBtn">Sair</button></div>`;$('#logoutBtn').onclick=()=>signOut(auth)}
function renderStats(){const p=state.profile;if(!p)return;$('#welcomeName').textContent=`Paz de Deus, ${p.displayName||'jovem'}!`;$('#statPoints').textContent=num(p.points);$('#statLevel').textContent=num(p.level,1);$('#statXp').textContent=`${num(p.xp)} XP`;$('#statAnswered').textContent=`${num(p.answered)} perguntas`;$('#statAccuracy').textContent=p.answered?`${Math.round(num(p.correct)/num(p.answered)*100)}%`:'0%'}
function renderMissions(){const html=MISSIONS.map(m=>{const cur=num(state.profile?.[m.key]);const pct=Math.min(100,Math.round(cur/m.target*100));return `<div class="mission"><div class="mission-top"><div><strong>${m.name}</strong><small class="muted">${m.type} • recompensa ${m.reward} XP</small></div><b>${cur}/${m.target}</b></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('');$('#homeMissions').innerHTML=html;$('#missionsList').innerHTML=html}
function renderUnlockPreview(){const p=state.profile||{};const items=[...BORDERS.filter(b=>!isUnlockedWithProfile(b,BORDER_REQUIREMENTS,p)).slice(0,2).map(b=>['Moldura '+b,BORDER_REQUIREMENTS[b][0]]),...TITLES.filter(t=>!isUnlockedWithProfile(t,TITLE_REQUIREMENTS,p)).slice(0,2).map(t=>['Título '+t,TITLE_REQUIREMENTS[t][0]])];$('#unlockPreview').innerHTML=items.map(i=>`<div class="mission"><strong>${esc(i[0])}</strong><small class="muted">${esc(i[1])}</small></div>`).join('')||'<div class="empty">Você já liberou tudo nesta versão.</div>'}
function renderJourney(){const groups=[{name:'Antigo Testamento',value:'AT',type:'testament'},{name:'Novo Testamento',value:'NT',type:'testament'},...books];$('#journeyGrid').innerHTML=groups.map(g=>`<button class="journey-card" data-journey="${esc(g.book||g.value)}" data-kind="${g.type||'book'}"><strong>${esc(g.name||g.book)}</strong><small>${g.type?'Trilha por testamento':`${g.testament} • ${g.count} perguntas`}</small></button>`).join('');$$('[data-journey]').forEach(btn=>btn.onclick=()=>{const kind=btn.dataset.kind;const val=btn.dataset.journey;openSoloModal(kind==='testament'?{testament:val}:{book:val})})}
function renderProfile(){const p=state.profile;if(!p)return;state.selectedAvatar=p.avatarId||'pergaminho';state.selectedBorder=isBorderUnlocked(p.borderId)?p.borderId:'simples';state.selectedTitle=isTitleUnlocked(p.activeTitle)?p.activeTitle:'Novo Discípulo';$('#profileAvatar').src=avatarSrc({...p,avatarId:state.selectedAvatar,borderId:state.selectedBorder,activeTitle:state.selectedTitle});$('#profileBorder').src=borderSrc(state.selectedBorder);$('#profileName').textContent=p.displayName||'Usuário';$('#profileTitle').textContent=state.selectedTitle;$('#profileMeta').textContent=`Nível ${num(p.level,1)} • ${num(p.points)} pontos`;$('#profileNameInput').value=p.displayName||'';$('#privacyMode').value=p.privacy||'public';$('#avatarMode').value=p.avatarMode||'preset';$('#avatarChoices').innerHTML=AVATARS.map(a=>`<button class="choice ${a===state.selectedAvatar?'active':''}" data-avatar="${a}"><img src="assets/avatars/${a}.svg" alt=""><span>${esc(a)}</span></button>`).join('');$('#borderChoices').innerHTML=BORDERS.map(b=>{const ok=isBorderUnlocked(b);return `<button class="choice ${b===state.selectedBorder?'active':''} ${ok?'':'locked'}" data-border="${b}" ${ok?'':'disabled'}><img src="assets/borders/${b}.svg" alt=""><span>${esc(b)}</span><small>${ok?'Liberada':esc(BORDER_REQUIREMENTS[b][0])}</small></button>`}).join('');$('#titleChoices').innerHTML=TITLES.map(t=>{const ok=isTitleUnlocked(t);return `<button class="choice ${t===state.selectedTitle?'active':''} ${ok?'':'locked'}" data-title="${esc(t)}" ${ok?'':'disabled'}><span>${esc(t)}</span><small>${ok?'Liberado':esc(TITLE_REQUIREMENTS[t][0])}</small></button>`}).join('');$$('[data-avatar]').forEach(b=>b.onclick=()=>{state.selectedAvatar=b.dataset.avatar;$('#profileAvatar').src=avatarSrc({...p,avatarId:state.selectedAvatar,avatarMode:$('#avatarMode').value});renderChoiceActive('#avatarChoices','avatar',state.selectedAvatar)});$$('[data-border]').forEach(b=>b.onclick=()=>{if(!isBorderUnlocked(b.dataset.border))return toast('Moldura bloqueada.');state.selectedBorder=b.dataset.border;$('#profileBorder').src=borderSrc(state.selectedBorder);renderChoiceActive('#borderChoices','border',state.selectedBorder)});$$('[data-title]').forEach(b=>b.onclick=()=>{if(!isTitleUnlocked(b.dataset.title))return toast('Título bloqueado.');state.selectedTitle=b.dataset.title;$('#profileTitle').textContent=state.selectedTitle;renderChoiceActive('#titleChoices','title',state.selectedTitle)})}
function renderChoiceActive(root,key,val){$$(`${root} .choice`).forEach(c=>c.classList.toggle('active',c.dataset[key]===val))}
function renderAll(){renderAuth();renderStats();renderMissions();renderUnlockPreview();renderJourney();renderProfile()}

function filteredQuestions(opts={}){let list=QUESTION_BANK.filter(q=>q.active!==false);if(opts.testament&&opts.testament!=='all')list=list.filter(q=>q.testament===opts.testament);if(opts.difficulty&&opts.difficulty!=='all')list=list.filter(q=>q.difficulty===opts.difficulty);if(opts.category&&opts.category!=='all')list=list.filter(q=>q.category===opts.category);if(opts.book)list=list.filter(q=>q.book===opts.book);return shuffle(list).slice(0,Math.max(1,num(opts.count,10)))}
function openModal(title,body){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><header class="modal-head"><h2>${esc(title)}</h2><button class="secondary" data-close>Fechar</button></header><div class="modal-body">${body}</div></section></div>`;root.querySelector('[data-close]').onclick=()=>root.innerHTML='';root.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))root.innerHTML=''};return root.querySelector('.modal-body')}
function openSoloModal(seed={}){const opts=categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const body=openModal('Quiz Solo',`<div class="quiz-config"><label>Testamento<select id="qTestament"><option value="all">Toda Bíblia</option><option value="AT">Antigo Testamento</option><option value="NT">Novo Testamento</option></select></label><label>Dificuldade<select id="qDifficulty"><option value="all">Todas</option><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option><option value="extremo">Extremo</option></select></label><label>Tema<select id="qCategory"><option value="all">Todos</option>${opts}</select></label><label>Perguntas<select id="qCount"><option>5</option><option selected>10</option><option>15</option><option>20</option></select></label></div><button class="primary full" id="startQuizBtn">Iniciar quiz</button><div id="quizStage" class="quiz-stage"><div class="empty">Configure e inicie. A resposta, explicação e referência aparecem após cada questão.</div></div>`);if(seed.testament)$('#qTestament').value=seed.testament;if(seed.category)$('#qCategory').value=seed.category;$('#startQuizBtn').onclick=()=>startQuiz({...seed,testament:$('#qTestament').value,difficulty:$('#qDifficulty').value,category:$('#qCategory').value,count:$('#qCount').value},'#quizStage')}
function startQuiz(opts={},target='#quizStage'){const qs=filteredQuestions(opts);if(!qs.length){$(target).innerHTML='<div class="empty">Nenhuma pergunta encontrada para estes filtros.</div>';return}state.quiz={questions:qs,index:0,score:0,correct:0,startedAt:Date.now(),target,answered:false};renderQuestion()}
function renderQuestion(){const qz=state.quiz,q=qz.questions[qz.index],total=qz.questions.length;$(qz.target).innerHTML=`<div class="question-card"><div class="question-top"><span class="tag">${esc(q.testament)} • ${esc(q.book)} • ${esc(q.difficulty)}</span><strong>${qz.index+1}/${total}</strong></div><div class="timer"><i></i></div><h3>${esc(q.question)}</h3><div class="answer-grid">${q.options.map(o=>`<button class="answer" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div id="questionFeedback"></div></div>`;qz.answered=false;$$('[data-answer]').forEach(b=>b.onclick=()=>answerQuestion(b.dataset.answer))}
async function answerQuestion(ans){const qz=state.quiz;if(!qz||qz.answered)return;qz.answered=true;const q=qz.questions[qz.index];const ok=ans===q.answer;const fast=(Date.now()-qz.startedAt)<9000;const pts=ok?pointsFor(q,fast):0;if(ok){qz.correct++;qz.score+=pts}else saveReview(q);$$('[data-answer]').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct');if(b.dataset.answer===ans&&!ok)b.classList.add('wrong')});$('#questionFeedback').innerHTML=`<div class="feedback"><strong>${ok?'Resposta correta':'Resposta correta: '+esc(q.answer)}</strong><br><span>Referência: ${esc(q.reference)} • Versão: ${esc(q.version||'JFA')}</span><p>${esc(q.explanation)}</p><div class="quick-actions"><button class="primary" id="nextQ">${qz.index+1===qz.questions.length?'Finalizar':'Próxima'}</button><button class="secondary" id="reportQ">Reportar pergunta</button></div></div>`;$('#nextQ').onclick=()=>nextQuestion();$('#reportQ').onclick=()=>reportQuestion(q);await applyQuizProgress(q,ok,pts)}
async function nextQuestion(){const qz=state.quiz;if(!qz)return;if(qz.index+1>=qz.questions.length){$(qz.target).innerHTML=`<div class="empty"><h3>Resultado</h3><p>Você acertou <strong>${qz.correct}/${qz.questions.length}</strong> e fez <strong>${qz.score}</strong> pontos.</p><button class="primary" id="finishQuizBtn">Concluir</button></div>`;$('#finishQuizBtn').onclick=()=>{$('#modalRoot').innerHTML='';refreshProfile()};await refreshProfile();return}qz.index++;renderQuestion()}
async function applyQuizProgress(q,ok,pts){if(!state.user)return;const data={answered:increment(1),answeredToday:increment(1),answeredWeek:increment(1),updatedAt:serverTimestamp()};if(ok){Object.assign(data,{correct:increment(1),correctToday:increment(1),points:increment(pts),weeklyPoints:increment(pts),monthlyPoints:increment(pts),xp:increment(pts),level:levelFor(num(state.profile.xp)+pts)});if(['dificil','extremo'].includes(q.difficulty))data.hardCorrectWeek=increment(1)}await updateDoc(doc(db,'users',state.user.uid),data);state.profile={...state.profile,answered:num(state.profile.answered)+1,answeredToday:num(state.profile.answeredToday)+1,answeredWeek:num(state.profile.answeredWeek)+1,updatedAt:null};if(ok){state.profile.correct=num(state.profile.correct)+1;state.profile.correctToday=num(state.profile.correctToday)+1;state.profile.points=num(state.profile.points)+pts;state.profile.weeklyPoints=num(state.profile.weeklyPoints)+pts;state.profile.monthlyPoints=num(state.profile.monthlyPoints)+pts;state.profile.xp=num(state.profile.xp)+pts;state.profile.level=levelFor(state.profile.xp);if(['dificil','extremo'].includes(q.difficulty))state.profile.hardCorrectWeek=num(state.profile.hardCorrectWeek)+1}renderStats();renderMissions();renderUnlockPreview()}
function saveReview(q){const arr=JSON.parse(localStorage.getItem('reviewBank')||'[]').filter(x=>x.id!==q.id);arr.unshift(q);localStorage.setItem('reviewBank',JSON.stringify(arr.slice(0,60)))}function renderReview(){const arr=JSON.parse(localStorage.getItem('reviewBank')||'[]');$('#reviewList').innerHTML=arr.map(q=>`<div class="card"><h3>${esc(q.question)}</h3><p><strong>Resposta:</strong> ${esc(q.answer)}</p><p class="muted">${esc(q.reference)} • ${esc(q.explanation)}</p></div>`).join('')||'<div class="empty">Nenhuma pergunta em revisão.</div>'}
async function reportQuestion(q){if(!state.user)return toast('Entre para reportar.');await addDoc(collection(db,'questionReports'),{questionId:q.id,question:q.question,reference:q.reference,reportedBy:state.user.uid,status:'open',createdAt:serverTimestamp()});toast('Reporte enviado para revisão.')}

async function loadRanking(){const box=$('#rankingList');box.innerHTML='<div class="empty">Carregando classificação...</div>';const mode=$('#rankingMode').value;const snap=await getDocs(query(collection(db,'users'),limit(200))).catch(()=>null);let rows=(snap?.docs||[]).map(d=>d.data()).filter(u=>(u.privacy||'public')==='public');rows.sort((a,b)=>num(b[mode])-num(a[mode]));box.innerHTML=rows.slice(0,50).map((u,i)=>`<div class="rank-row"><span class="rank-pos">${i+1}</span><div><strong>${esc(u.displayName||'Usuário')}</strong><small class="muted">${esc(u.activeTitle||'Novo Discípulo')} • nível ${num(u.level,1)}</small></div><strong>${num(u[mode])}</strong></div>`).join('')||'<div class="empty">Nenhum usuário público encontrado.</div>'}
async function sendFriend(){const email=$('#friendEmail').value.trim().toLowerCase();if(!email)return toast('Digite o e-mail.');if(email===state.profile.email)return toast('Use o e-mail de outra pessoa.');const snap=await getDocs(query(collection(db,'users'),where('email','==',email),limit(1))).catch(()=>null);if(!snap||snap.empty)return toast('Usuário não encontrado.');const target=snap.docs[0].data();await addDoc(collection(db,'friendRequests'),{from:state.user.uid,fromName:state.profile.displayName,fromEmail:state.profile.email,to:target.uid,toEmail:target.email,status:'pending',createdAt:serverTimestamp()});await updateDoc(doc(db,'users',state.user.uid),{friendInvites:increment(1)});toast('Convite enviado.');$('#friendEmail').value='';loadFriends();refreshProfile()}
async function loadFriends(){const box=$('#friendsList');box.innerHTML='<div class="empty">Carregando...</div>';const sent=await getDocs(query(collection(db,'friendRequests'),where('from','==',state.user.uid),limit(50))).catch(()=>null);const rec=await getDocs(query(collection(db,'friendRequests'),where('to','==',state.user.uid),limit(50))).catch(()=>null);let rows=[];sent?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${esc(f.toEmail)}</strong><small class="muted">Convite enviado</small></div><span class="tag">${esc(f.status)}</span></div>`)});rec?.forEach(d=>{const f=d.data();rows.push(`<div class="friend-row"><div><strong>${esc(f.fromName)}</strong><small class="muted">${esc(f.fromEmail)}</small></div>${f.status==='pending'?`<button class="secondary" data-accept="${d.id}">Aceitar</button>`:`<span class="tag">Aceito</span>`}</div>`)});box.innerHTML=rows.join('')||'<div class="empty">Nenhum convite ainda.</div>';$$('[data-accept]').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'friendRequests',b.dataset.accept),{status:'accepted',acceptedAt:serverTimestamp()});toast('Amizade aceita.');loadFriends()})}

function openRoomModal(){openModal('Desafio entre Irmãos',`<div class="room-grid"><article class="panel flat"><h3>Criar sala</h3><label>Nome da sala<input id="roomName" value="Desafio da Mocidade"></label><div class="settings-grid"><label>Dificuldade<select id="roomDifficulty"><option value="all">Todas</option><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option><option value="extremo">Extremo</option></select></label><label>Testamento<select id="roomTestament"><option value="all">Toda Bíblia</option><option value="AT">AT</option><option value="NT">NT</option></select></label><label>Perguntas<input id="roomQuestions" type="number" min="3" max="30" value="5"></label><label>Tempo/min<input id="roomMinutes" type="number" min="1" max="60" value="10"></label></div><button class="primary full" id="createRoomBtn">Criar sala</button></article><article class="panel flat"><h3>Entrar</h3><label>Código da sala<input id="joinCode" placeholder="JFA-1234"></label><button class="secondary full" id="joinRoomBtn">Entrar por código</button><hr><div id="roomLive" class="room-live"><div class="empty">Nenhuma sala ativa neste dispositivo.</div></div></article></div>`);$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;if(state.roomId)watchRoom(state.roomId)}
async function createRoom(){const code='JFA-'+Math.random().toString(36).slice(2,6).toUpperCase();const data={code,name:$('#roomName').value||'Desafio da Mocidade',leader:state.user.uid,leaderName:state.profile.displayName,status:'open',members:[state.user.uid],memberNames:{[state.user.uid]:state.profile.displayName},settings:{difficulty:$('#roomDifficulty').value,testament:$('#roomTestament').value,questions:num($('#roomQuestions').value,5),minutes:num($('#roomMinutes').value,10)},createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const ref=await addDoc(collection(db,'rooms'),data);state.roomId=ref.id;await updateDoc(doc(db,'users',state.user.uid),{roomsJoined:increment(1)});toast(`Sala criada: ${code}`);watchRoom(ref.id);refreshProfile()}
async function joinRoom(){const code=$('#joinCode').value.trim().toUpperCase();if(!code)return toast('Digite o código.');const snap=await getDocs(query(collection(db,'rooms'),where('code','==',code),limit(1))).catch(()=>null);if(!snap||snap.empty)return toast('Sala não encontrada.');const d=snap.docs[0];await updateDoc(doc(db,'rooms',d.id),{members:arrayUnion(state.user.uid),[`memberNames.${state.user.uid}`]:state.profile.displayName,updatedAt:serverTimestamp()});state.roomId=d.id;await updateDoc(doc(db,'users',state.user.uid),{roomsJoined:increment(1)});toast('Você entrou na sala.');watchRoom(d.id);refreshProfile()}
function watchRoom(id){state.roomUnsub?.();state.roomUnsub=onSnapshot(doc(db,'rooms',id),snap=>{if(!snap.exists()){state.roomId=null;const box=$('#roomLive');if(box)box.innerHTML='<div class="empty">Sala fechada.</div>';return}renderRoom(id,snap.data())})}
function renderRoom(id,r){const box=$('#roomLive');if(!box)return;const isLeader=r.leader===state.user.uid;const members=r.members||[];box.innerHTML=`<div class="card"><h3>${esc(r.name)}</h3><p class="muted">Código: <strong>${esc(r.code)}</strong> • status: ${esc(r.status)}</p><p class="muted">${esc(r.settings?.questions)} perguntas • ${esc(r.settings?.minutes)} min • ${esc(r.settings?.difficulty)} • ${esc(r.settings?.testament)}</p></div><div class="member-list">${members.map(uid=>`<div class="member"><span>${esc(r.memberNames?.[uid]||uid)} ${uid===r.leader?'<small class="tag">líder</small>':''}</span>${isLeader&&uid!==state.user.uid?`<button class="secondary" data-kick="${uid}">Remover</button>`:''}</div>`).join('')}</div>${isLeader?`<div class="inline-form"><input id="addMemberEmail" placeholder="email para adicionar"><button class="secondary" id="addMemberBtn">Adicionar</button></div><div class="quick-actions"><button class="primary" id="startRoomBtn">Iniciar partida</button><button class="secondary" id="transferBtn">Transferir liderança</button><button class="danger secondary" id="closeRoomBtn">Fechar grupo</button></div>`:`<button class="secondary full" id="leaveRoomBtn">Sair da sala</button>`}`;$$('[data-kick]').forEach(b=>b.onclick=()=>removeRoomMember(id,b.dataset.kick));$('#addMemberBtn')&&($('#addMemberBtn').onclick=()=>addRoomMemberByEmail(id));$('#startRoomBtn')&&($('#startRoomBtn').onclick=()=>startRoomGame(id,r));$('#transferBtn')&&($('#transferBtn').onclick=()=>transferLeadership(id,r));$('#closeRoomBtn')&&($('#closeRoomBtn').onclick=()=>updateDoc(doc(db,'rooms',id),{status:'closed',members:[],updatedAt:serverTimestamp()}).then(()=>toast('Grupo fechado.')));$('#leaveRoomBtn')&&($('#leaveRoomBtn').onclick=()=>removeRoomMember(id,state.user.uid))}
async function addRoomMemberByEmail(id){const email=$('#addMemberEmail').value.trim().toLowerCase();const snap=await getDocs(query(collection(db,'users'),where('email','==',email),limit(1))).catch(()=>null);if(!snap||snap.empty)return toast('Usuário não encontrado.');const u=snap.docs[0].data();await updateDoc(doc(db,'rooms',id),{members:arrayUnion(u.uid),[`memberNames.${u.uid}`]:u.displayName||u.email,updatedAt:serverTimestamp()});toast('Membro adicionado.')}
async function removeRoomMember(id,uid){await updateDoc(doc(db,'rooms',id),{members:arrayRemove(uid),updatedAt:serverTimestamp()});if(uid===state.user.uid)state.roomId=null;toast('Membro removido.')}
async function transferLeadership(id,r){const next=(r.members||[]).find(uid=>uid!==state.user.uid);if(!next)return toast('Adicione outro membro antes.');await updateDoc(doc(db,'rooms',id),{leader:next,leaderName:r.memberNames?.[next]||'Novo líder',updatedAt:serverTimestamp()});toast('Liderança transferida.')}
async function startRoomGame(id,r){await updateDoc(doc(db,'rooms',id),{status:'playing',startedAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Partida iniciada. Use o quiz solo com a configuração da sala para pontuar.')}

async function createTournament(){const ref=await addDoc(collection(db,'tournaments'),{name:'Campeonato da Semana da Mocidade',theme:'Evangelhos, Atos e Doutrina Bíblica',status:'open',createdBy:state.user.uid,participants:[state.user.uid],participantNames:{[state.user.uid]:state.profile.displayName},scores:{[state.user.uid]:0},createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Campeonato criado.');loadTournaments();return ref.id}
async function loadTournaments(){const box=$('#tournamentList');box.innerHTML='<div class="empty">Carregando campeonatos...</div>';const snap=await getDocs(query(collection(db,'tournaments'),limit(50))).catch(()=>null);const rows=(snap?.docs||[]).sort((a,b)=>num(b.data().createdAt?.seconds)-num(a.data().createdAt?.seconds));box.innerHTML=rows.map(d=>{const t=d.data();const joined=(t.participants||[]).includes(state.user.uid);return `<div class="card"><h3>${esc(t.name)}</h3><p class="muted">Tema: ${esc(t.theme)} • ${esc(t.status)} • ${(t.participants||[]).length} participante(s)</p><button class="secondary" data-join-t="${d.id}" ${joined?'disabled':''}>${joined?'Participando':'Participar'}</button></div>`}).join('')||'<div class="empty">Nenhum campeonato criado.</div>';$$('[data-join-t]').forEach(b=>b.onclick=()=>joinTournament(b.dataset.joinT))}
async function joinTournament(id){await updateDoc(doc(db,'tournaments',id),{participants:arrayUnion(state.user.uid),[`participantNames.${state.user.uid}`]:state.profile.displayName,[`scores.${state.user.uid}`]:0,updatedAt:serverTimestamp()});toast('Você entrou no campeonato.');loadTournaments()}
async function syncQuestions(){if(!state.isAdmin)return toast('Apenas admin.');for(let i=0;i<QUESTION_BANK.length;i+=450){const batch=writeBatch(db);QUESTION_BANK.slice(i,i+450).forEach(q=>batch.set(doc(db,'questions',q.id),q));await batch.commit()}toast('Perguntas sincronizadas.')}
async function addQuestion(){try{const q=JSON.parse($('#adminQuestionJson').value);if(!q.question||!q.options||!q.answer)return toast('JSON incompleto.');q.id=q.id||`custom-${Date.now()}`;q.version=q.version||'JFA';q.active=q.active!==false;await setDoc(doc(db,'questions',q.id),q);toast('Pergunta adicionada.')}catch(e){toast('JSON inválido.')}}async function loadReports(){const snap=await getDocs(query(collection(db,'questionReports'),where('status','==','open'),limit(50))).catch(()=>null);$('#adminReports').innerHTML=(snap?.docs||[]).map(d=>{const r=d.data();return `<div class="card"><h3>${esc(r.questionId)}</h3><p>${esc(r.question)}</p><small class="muted">${esc(r.reference)}</small></div>`}).join('')||'<div class="empty">Sem reportes abertos.</div>'}

function bind(){document.body.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){e.preventDefault();setRoute(route)}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='solo-modal')openSoloModal();if(action==='room-modal')openRoomModal()});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#toggleEmailBtn').onclick=()=>$('#emailForm').classList.toggle('hidden');$('#googleLoginBtn').onclick=()=>signInWithPopup(auth,provider).catch(e=>toast(e.message));$('#emailCreateBtn').onclick=async()=>{try{const c=await createUserWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value);if($('#displayNameInput').value)await updateProfile(c.user,{displayName:$('#displayNameInput').value})}catch(e){$('#authMessage').textContent=e.message}};$('#emailLoginBtn').onclick=()=>signInWithEmailAndPassword(auth,$('#emailInput').value,$('#passwordInput').value).catch(e=>$('#authMessage').textContent=e.message);$('#clearReviewBtn').onclick=()=>{localStorage.removeItem('reviewBank');renderReview()};$('#refreshRankingBtn').onclick=loadRanking;$('#rankingMode').onchange=loadRanking;$('#sendFriendBtn').onclick=sendFriend;$('#newTournamentBtn').onclick=createTournament;$('#saveProfileBtn').onclick=saveProfile;$('#syncQuestionsBtn').onclick=syncQuestions;$('#addQuestionBtn').onclick=addQuestion;$('#loadReportsBtn').onclick=loadReports;$('#avatarMode').onchange=()=>{$('#profileAvatar').src=avatarSrc({...state.profile,avatarMode:$('#avatarMode').value,avatarId:state.selectedAvatar})};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{state.deferredInstall?.prompt();state.deferredInstall=null;$('#installBtn').classList.add('hidden')}}
async function saveProfile(){if(!isBorderUnlocked(state.selectedBorder))return toast('Moldura bloqueada.');if(!isTitleUnlocked(state.selectedTitle))return toast('Título bloqueado.');const data={displayName:$('#profileNameInput').value.trim()||state.profile.displayName,privacy:$('#privacyMode').value,avatarMode:$('#avatarMode').value,avatarId:state.selectedAvatar,borderId:state.selectedBorder,activeTitle:state.selectedTitle,updatedAt:serverTimestamp()};await updateDoc(doc(db,'users',state.user.uid),data);state.profile={...state.profile,...data};toast('Perfil salvo.');renderAll()}

bind();if('serviceWorker' in navigator)navigator.serviceWorker.register('/src/js/sw.js').catch(()=>{});
onAuthStateChanged(auth,async user=>{state.user=user;if(!user){state.profile=null;$('#authGate').classList.remove('hidden');$('#appContent').classList.add('hidden');renderAuth();return}state.profile=await ensureProfile(user);await checkAdmin(user.uid);$('#authGate').classList.add('hidden');$('#appContent').classList.remove('hidden');renderAll();setRoute('home')});
